services:
    client:
        container_name: plainsql_container
        build:
            context: .
        ports:
            - '3004:3000'
        environment:
            - NODE_ENV=production
        networks:
            - plainsql_network

networks:
    plainsql_network:
        driver: bridge
